{% set name = "dbt-duckdb" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 11308af4ad567b4fac0417fc2adfcb85b7021f92dff2b441bca30785f292f933

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - pbr
  run:
    - python >=3.8
    - dbt-common >=1,<2
    - dbt-adapters >=1,<2
    - dbt-core >=1.8.0
    - python-duckdb >=0.9.0

test:
  imports:
    - dbt
    - dbt.adapters.duckdb
    - dbt.adapters.duckdb.environments
    - dbt.adapters.duckdb.plugins
    - dbt.include.duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jwills/dbt-duckdb
  summary: The duckdb adapter plugin for dbt (data build tool)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexanderThebeltQC
    - SaravananSathyanandhaQC
