{% set name = "dbt-duckdb" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-duckdb-{{ version }}.tar.gz
  sha256: 4767743f9e437a74b94722984bf7ae201e91f83ef7eb8023850a970b1fb7505c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dbt-core >=1.7.0,<1.8
    - python-duckdb >=0.9.0

test:
  imports:
    - dbt
    - dbt.adapters.duckdb
    - dbt.adapters.duckdb.environments
    - dbt.adapters.duckdb.plugins
    - dbt.include.duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jwills/dbt-duckdb
  summary: The duckdb adapter plugin for dbt (data build tool)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexanderThebeltQC
    - SaravananSathyanandhaQC
