{% set name = "dbt-duckdb" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-duckdb-{{ version }}.tar.gz
  sha256: 66afaa1b43b57547c7daed74d8b1b335a02c537f49bb055e613da1f477ac9d5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dbt-core >=1.6.0,<1.7
    - python-duckdb >=0.7.0

test:
  imports:
    - dbt
    - dbt.adapters.duckdb
    - dbt.adapters.duckdb.environments
    - dbt.adapters.duckdb.plugins
    - dbt.include.duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jwills/dbt-duckdb
  summary: The duckdb adapter plugin for dbt (data build tool)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexanderThebeltQC
    - SaravananSathyanandhaQC
